apiVersion: v1
kind: Service
metadata:
  name: {{ include "lucis-nft-web.fullname" . }}
  labels:
    {{- include "lucis-nft-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "lucis-nft-web.selectorLabels" . | nindent 4 }}
